[[integrations]]
name = "snooty-cache-plugin"

[build]
publish = "snooty/public"
command = ". ./build.sh"

[[redirects]]
from = "/mapping-rules/calculated-fields/calculated-fields"
to = "/mapping-rules/fields/calculated-fields/calculated-fields"
