[[integrations]]
name = "snooty-cache-plugin"

[build]
publish = "snooty/public"
command = ". ./build.sh"

# Redirect calculated fields to new drawer introduced in DOCSP-32370 - Field Customizations
# Field Customization
[[redirects]]
from = "/mapping-rules/calculated-fields/calculated-fields/*"
to = "/mapping-rules/fields/calculated-fields/calculated-fields*"

[[redirects]]
from = "/mapping-rules/calculated-fields/calculated-fields/add-calculated-fields"
to = "/mapping-rules/fields/calculated-fields/calculated-fields/add-calculated-fields"


# Redirect for previous Code Generation Page DOCSP-33055 - Prep Code Generation
[[redirects]]
from = "/code-generation/code-generation"
to = "/code-generation"

# DOCS-16498 Getting Started Page Start
[[redirects]]
from = "/migration-scenarios"
to = "/getting-started/migration-scenarios"

[[redirects]]
from = "/supported-databases"
to = "/getting-started/supported-databases"
